// Generated by CoffeeScript 1.9.0
var changetab, closetab, createpage, currenttab, elementids, opendesigner, openprew, opentab, tabs,
  __indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

currenttab = 0;

tabs = [];

elementids = [];

opentab = (function(_this) {
  return function(tabtitle, name) {
    if (__indexOf.call(tabs, name) >= 0) {
      return changetab(name);
    } else {
      return $.get('tab.' + name + '.html', function(data) {
        var tab;
        $('#leftp').css('display', 'none');
        $('#rightp').css('display', 'none');
        $('#tabss').append("<button id=\"btn" + name + "\" type=\"button\" onclick=\"changetab('" + name + "')\" class=\"btn btn-default\">\n" + tabtitle + " <a onclick=\"closetab('" + name + "')\">x</a>\n</button>");
        tab = $("<div>", {
          id: 'tab' + name
        }).html(data);
        $('#' + tabs[currenttab]).css('display', 'none');
        tabs.push(name);
        currenttab = tabs.indexOf(name);
        $('#tabw').append(tab);
        return $('#center').attr("class", "col-md-12");
      });
    }
  };
})(this);

changetab = (function(_this) {
  return function(name) {
    $('#tab' + tabs[currenttab]).css('display', 'none');
    $('#tab' + name).css('display', 'block');
    currenttab = tabs.indexOf(name);
    if ($('#tab' + name).attr('designer') === 'true') {
      $('#center').attr("class", "col-md-8");
      $('#leftp').css('display', 'block');
      return $('#rightp').css('display', 'block');
    } else if (currenttab === -1) {
      $('#center').attr("class", "col-md-8");
      $('#leftp').css('display', 'block');
      return $('#rightp').css('display', 'none');
    } else {
      $('#center').attr("class", "col-md-12");
      $('#leftp').css('display', 'none');
      return $('#rightp').css('display', 'none');
    }
  };
})(this);

closetab = (function(_this) {
  return function(name) {
    var _ref;
    $('#tab' + name).remove();
    $('#btn' + name).remove();
    if (tabs[currenttab] === name) {
      changetab(tabs[currenttab - ((_ref = currenttab > 1) != null ? _ref : {
        1: -1
      })]);
    }
    return tabs.splice(tabs.indexOf(name), 1);
  };
})(this);

opendesigner = (function(_this) {
  return function(pagetitle, page) {
    return $.post('/page', {
      'p': page
    }, function(data) {
      var designer;
      $('#center').attr("class", "col-md-8");
      $('#leftp').css('display', 'block');
      $('#rightp').css('display', 'block');
      $('#tab' + tabs[currenttab]).css('display', 'none');
      tabs.push(page);
      currenttab = tabs.length;
      $('#tabss').append("<button id=\"btn" + page + "\" type=\"button\" onclick=\"changetab('" + page + "')\" class=\"btn btn-default\">\n" + pagetitle + " <a onclick=\"closetab('" + page + "')\">x</a>\n</button>");
      designer = $("<itemdrop-element>").html(data);
      designer.attr('designer', 'true');
      designer.attr('id', 'drp' + page);
      return $('#tabw').append(designer);
    });
  };
})(this);

createpage = (function(_this) {
  return function() {
    var pagename;
    pagename = prompt("Sayfa Adını Girin");
    if (pagename != null) {
      $.post('/page/new', {
        pagedata: {
          page: pagename,
          body: '<html></html>'
        },
        id: pID
      });
    }
    return rData();
  };
})(this);

openprew = (function(_this) {
  return function(pagetitle, page) {
    return $.get('/page?p=#{page}', function(data) {
      var tab;
      $('#leftp').css('display', 'none');
      $('#rightp').css('display', 'none');
      $('#tabss').append("<button id=\"btn" + page + "\" type=\"button\" onclick=\"changetab('" + page + "')\" class=\"btn btn-default\">\n" + pagetitle + " <a onclick=\"closetab('" + page + "')\">x</a>\n</button>");
      tab = $("<div>", {
        id: "tab" + page
      }).html(data);
      $('#tab' + tabs[currenttab]).css('display', 'none');
      tabs.push(page);
      currenttab = tabs.length;
      $('#tabw').append(tab);
      return $('#center').attr("class", "col-md-12");
    });
  };
})(this);
